# Generated by Django 2.0 on 2018-01-10 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0002_auto_20171219_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='cat_image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
