# Generated by Django 2.0 on 2018-01-10 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0003_category_cat_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cat_image',
            field=models.ImageField(blank=True, null=True, upload_to='category_images/'),
        ),
    ]
