# Generated by Django 2.0 on 2018-01-10 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0004_auto_20180110_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cat_image',
            field=models.ImageField(blank=True, null=True, upload_to='static/category_images/'),
        ),
    ]
