# Generated by Django 2.0 on 2018-01-12 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0005_auto_20180111_0031'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_ad',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='static/product_images/'),
        ),
        migrations.AlterField(
            model_name='product_ad',
            name='ad_title',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='product_ad',
            name='product_description',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
